# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
